### ISSUE TITLE
Page overlay in mobile devices. 

### ISSUE THREAD

**Issue by Vivek2509** [hirejuniors-dev/front-end#19]
**About page and footer is overlay**
On mobile device About page and footer are overlaying.

**Screenshots**
![Mobile Screenshot](https://user-images.githubusercontent.com/43227010/103471414-15c3de80-4da6-11eb-8f0c-2e595b904838.jpeg)
![Firefox Screenshot](https://user-images.githubusercontent.com/43227010/103471422-2ffdbc80-4da6-11eb-985d-304f2ca72e51.png)

**Smartphone:**
 - Device: [Mi a3]
 - OS: [Android:10]
 - Browser [Chrome, firefox]
 - Version [87,84]

**Comment by harshil1712** [comment]
Thanks, @Vivek2509 for opening this issue. Let me know if you want to work on this 🙂

**Comment by imox2** [comment]
@harshil1712 I am working on this

**Comment by harshil1712** [comment]
Hey @imox2 👋 
Thanks for taking this! Assigning this issue to you.

**Comment by imox2** [comment]
@harshil1712 Thanks, I have opened a pr
