### ISSUE TITLE
Filters can't be clicked on on md+ views

### ISSUE THREAD

**Issue by Amorpheuz** [hirejuniors-dev/front-end#20]
**Describe the bug**
A negative `z-index` value is causing the filter values to hide under its parent div, which then doesn't allow to click on them.

**To Reproduce**
1. Go to https://hirejuniors.dev/ on a device with width `>768px`.
2. Try clicking on Filter checkboxes.
3. Open Dev Tools use the "Element Selector" present in top left of dev tools to hover on the Filter Area.
4. The parent div gets highlighted, indicating it gets stacked over child Filter div.

**Expected behavior**
Z-indexes are used in a correct manner to replicate current stacking behavior minus the filter div stacking behind parent.

**Screenshots**
![image](https://user-images.githubusercontent.com/22113778/103478509-45e2a000-4ded-11eb-8171-7af4ba8b09f7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox and Edge
 - Version: v85 and v87 respectively

**Smartphone (please complete the following information):**
- Not applicable to smartphones.

**Additional context**
Current implementation allocates a `z-index` of -1 to Filter div. Its preferrable to only use positive values to prevent such behavior.

**Comment by harshil1712** [comment]
Thanks, @Amorpheuz for opening this issue. Let me know if you want to work on this 🙂

**Comment by Amorpheuz** [comment]
Sure, I would love to take this up.

**Comment by harshil1712** [comment]
Thanks for solving this. Got merged and deployed 🚀
